# Generated by Django 3.0.6 on 2020-07-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_title',
            field=models.CharField(max_length=200),
        ),
    ]
